# Generated by Django 5.0.1 on 2025-02-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип занятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='classroom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Читающая кафедра'),
        ),
        migrations.AlterField(
            model_name='event',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='discipline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tutor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преподаватель (спикер)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='weekday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='День'),
        ),
    ]
