# Generated by Django 5.0.1 on 2025-02-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_group_event_type_alter_event_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата заяв')),
                ('full_name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('class_number', models.CharField(max_length=30, verbose_name='Класс')),
                ('school', models.CharField(max_length=999, verbose_name='Школа')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
