# Generated by Django 5.0.1 on 2025-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
