# Generated by Django 5.0.1 on 2024-01-29 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('max_teams', models.PositiveIntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('captain_fullname', models.CharField(max_length=255)),
                ('captain_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('captain_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.PositiveIntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.teams')),
            ],
        ),
    ]
