# Generated by Django 5.0.1 on 2024-01-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='choose_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='choose_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='choose_teams',
            field=models.BooleanField(default=False),
        ),
    ]
