# Generated by Django 5.0.1 on 2024-01-30 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='projects.team'),
        ),
    ]
