# Generated by Django 5.0.1 on 2024-01-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_customer_project_category_team_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
