# Generated by Django 5.0.1 on 2024-01-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_problem_project_target_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', to='projects.tag'),
        ),
    ]
