# Generated by Django 5.0.1 on 2024-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
