# Generated by Django 5.0.1 on 2024-04-03 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_team_group_name_team_tutor_email_team_tutor_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDSProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('problem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('course_title', models.CharField(blank=True, max_length=100, null=True)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('required_by', models.CharField(blank=True, max_length=100, null=True)),
                ('functionality', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('mentor_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='group_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CPDSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fathername', models.CharField(blank=True, max_length=255, null=True)),
                ('university_short', models.CharField(blank=True, max_length=255, null=True)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_link', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('questions', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.cpdsproject')),
            ],
        ),
    ]
