# Generated by Django 5.0.1 on 2024-04-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_cpdsproject_member_group_name_cpdsrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdsproject',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cpds_projects'),
        ),
    ]
