# Generated by Django 5.0.1 on 2024-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_cpdsproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdsproject',
            name='course_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название института'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='functionality',
            field=models.TextField(blank=True, null=True, verbose_name='Функционал'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cpds_projects', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Финальная презентация предыдущего этапа'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='mentor_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО наставника проекта'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='problem',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта, проблема'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='required_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кто требуется'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='required_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Что должен уметь'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус проекта (начинается или продолжается)'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='task',
            field=models.TextField(blank=True, null=True, verbose_name='Этап проекта (что предстоит сделать команде в течение семестра)'),
        ),
        migrations.AlterField(
            model_name='cpdsproject',
            name='team_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество человек в команде'),
        ),
    ]
