# Generated by Django 5.0.1 on 2024-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_cpdsproject_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdsproject',
            name='required_by',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Кто требуется'),
        ),
    ]
