# Generated by Django 5.0.1 on 2024-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_cpdsproject_required_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdsproject',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('progress', 'Продолжающийся')], default='new', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
