# Generated by Django 5.0.1 on 2024-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_cpdsproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdsproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
