# Generated by Django 5.0.1 on 2024-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_cpdsproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpdsproject',
            name='request_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на анкету'),
        ),
    ]
