# Generated by Django 5.0.1 on 2024-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_cpdsproject_request_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdsproject',
            name='required_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кто требуется'),
        ),
    ]
