# Generated by Django 5.0.1 on 2024-09-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_project_is_active_project_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tutor_fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
