# Generated by Django 5.0.1 on 2025-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_team_tutor_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='previous_project_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
