# Generated by Django 5.0.1 on 2025-02-11 10:36

from django.db import migrations, models


def copy_name_to_old_name(apps, schema_editor):
    Team = apps.get_model('projects', 'Team')
    for obj in Team.objects.all():
        if obj.previous_project_name and not obj.old_name:
            obj.old_name = obj.previous_project_name
            obj.save(update_fields=['old_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_team_previous_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='old_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(copy_name_to_old_name),
    ]
