# Generated by Django 5.0.1 on 2025-02-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
