# Generated by Django 5.0.1 on 2026-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_rename_settings_setting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'is_active'], name='projects_pr_categor_0ddb89_idx'),
        ),
    ]
